name: Backend Deployment

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy backend to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            if [ -d "$HOME/wedraw/.git" ]; then
              echo "Repository already exists"
              cd $HOME/wedraw
              git pull origin main
            else
              echo "First deployment: cloning repository"
              cd $HOME
              git clone https://github.com/Nishantkumar012/wedraw.git
              cd $HOME/wedraw
            fi

            echo "Go to backend"
            cd backend

            echo "Install dependencies (production only)"
            NODE_OPTIONS="--max-old-space-size=256" npm ci --only=production

            echo "Node and npm versions:"
            node -v
            npm -v

            echo "Generate Prisma Client"
            npx prisma generate

            echo "Run database migrations"
            npx prisma migrate deploy

            echo "Build TypeScript"
            npm run build

            echo "Stopping old backend process"
            pm2 delete backend || true

            echo "Starting backend with PM2"
            pm2 start dist/index.js --name backend --node-args="--max-old-space-size=512"

            echo "Save PM2 process"
            pm2 save
            pm2 startup